version: "3.9"


services:
  database:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB_FILE: /run/secrets/db_name
      POSTGRES_USER_FILE: /run/secrets/db_username
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - "5432:5432"
    secrets:
      - db_name
      - db_username
      - db_password
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      target: dev
      args:
        BACKEND_PORT: 8000
    secrets:
      - db_name
      - db_username
      - db_password
      - source: backend_secret_key
        target: secret_key
      - superuser_name
      - superuser_password
    ports:
      - "$BACKEND_PORT:8000"
    depends_on:
      - database

secrets:
  db_name:
    environment: DB_NAME
  db_username:
    environment: DB_USERNAME
  db_password:
    environment: DB_PASSWORD

  backend_secret_key:
    environment: BACKEND_SECRET_KEY
  superuser_name:
    environment: SUPERUSER_NAME
  superuser_password:
    environment: SUPERUSER_PASSWORD


volumes:
  db_data:
