# Generated by Django 4.2.1 on 2023-05-09 14:02

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name='UserEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('friends', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('outcoming_invites', models.ManyToManyField(related_name='incoming_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('name'), name='gin_trgm_ops'), name='user_name_gin_idx'), models.Index(fields=['name'], name='api_userent_name_4002d7_idx')],
            },
        ),
    ]
